const RAW_VOCAB = [
  ["大人", "おとな", "otona", "adult", "Nouns"],
  ["弁護士", "べんごし", "bengoshi", "lawyer", "Nouns"],
  ["私", "わたくし", "watakushi", "I / me (formal)", "Nouns"],
  ["カレー", "カレー", "karē", "curry", "Nouns"],
  ["紅茶", "こうちゃ", "kōcha", "black tea", "Nouns"],
  ["着物", "きもの", "kimono", "kimono; Japanese traditional dress", "Nouns"],
  ["セーター", "セーター", "sētā", "sweater", "Nouns"],
  ["楽器", "がっき", "gakki", "musical instrument", "Nouns"],
  ["空手", "からて", "karate", "karate", "Nouns"],
  ["ゴルフ", "ゴルフ", "gorufu", "golf", "Nouns"],
  ["バイク", "バイク", "baiku", "motorcycle", "Nouns"],
  ["象", "ぞう", "zō", "elephant", "Nouns"],
  ["体", "からだ", "karada", "body", "Nouns"],
  ["外国語", "がいこくご", "gaikokugo", "foreign language", "Nouns"],
  ["言葉", "ことば", "kotoba", "language / word", "Nouns"],
  ["文法", "ぶんぽう", "bunpō", "grammar", "Nouns"],
  ["アプリ", "アプリ", "apuri", "application / app", "Nouns"],
  ["アパート", "アパート", "apāto", "apartment; smaller apartment building", "Nouns"],
  ["マンション", "マンション", "manshon", "larger apartment building; condominium", "Nouns"],
  ["空港", "くうこう", "kūkō", "airport", "Nouns"],
  ["店", "みせ", "mise", "shop; store", "Nouns"],
  ["物価", "ぶっか", "bukka", "consumer prices", "Nouns"],
  ["広告", "こうこく", "kōkoku", "advertisement", "Nouns"],
  ["募集", "ぼしゅう", "boshū", "recruitment", "Nouns"],
  ["約束", "やくそく", "yakusoku", "promise; appointment", "Nouns"],
  ["うれしい", "うれしい", "ureshii", "glad / happy", "い-Adjectives"],
  ["悲しい", "かなしい", "kanashii", "sad", "い-Adjectives"],
  ["厳しい", "きびしい", "kibishii", "strict", "い-Adjectives"],
  ["気分が悪い", "きぶんがわるい", "kibun ga warui", "to feel sick", "い-Adjectives"],
  ["辛い", "からい", "karai", "hot and spicy; salty", "い-Adjectives"],
  ["すごい", "すごい", "sugoi", "incredible; awesome", "い-Adjectives"],
  ["近い", "ちかい", "chikai", "close; near", "い-Adjectives"],
  ["いろいろ（な）", "いろいろ（な）", "iroiro", "various; different kinds of", "な-Adjectives"],
  ["幸せ（な）", "しあわせ（な）", "shiawase", "happy; lasting happiness", "な-Adjectives"],
  ["だめ（な）", "だめ（な）", "dame", "no good", "な-Adjectives"],
  ["編む", "あむ", "amu", "to knit", "Verbs"],
  ["頑張る", "がんばる", "ganbaru", "to do one's best; to try hard", "Verbs"],
  ["泣く", "なく", "naku", "to cry", "Verbs"],
  ["磨く", "みがく", "migaku", "to brush (teeth); to polish", "Verbs"],
  ["約束を守る", "やくそくをまもる", "yakusoku o mamoru", "to keep a promise", "Verbs"],
  ["感動する", "かんどうする", "kandō suru", "to be moved / touched (by...)", "Verbs"],
  ["～回", "～かい", "~kai", "... times", "Adverbs & Expressions"],
  ["～キロ", "～キロ", "~kiro", "... kilometers; ... kilograms", "Adverbs & Expressions"],
  ["全部", "ぜんぶ", "zenbu", "all", "Adverbs & Expressions"],
  ["～と申します", "～ともうします", "~to mōshimasu", "my name is...", "Adverbs & Expressions"],
  ["特に", "とくに", "tokuni", "especially", "Adverbs & Expressions"],
  ["一日", "いちにち", "ichinichi", "one day", "Days & Counters"],
  ["二日", "ふつか", "futsuka", "two days", "Days & Counters"],
  ["三日", "みっか", "mikka", "three days", "Days & Counters"],
  ["四日", "よっか", "yokka", "four days", "Days & Counters"],
  ["五日", "いつか", "itsuka", "five days", "Days & Counters"],
  ["六日", "むいか", "muika", "six days", "Days & Counters"],
  ["七日", "なのか", "nanoka", "seven days", "Days & Counters"],
  ["八日", "ようか", "yōka", "eight days", "Days & Counters"],
  ["九日", "ここのか", "kokonoka", "nine days", "Days & Counters"],
  ["十日", "とおか", "tōka", "ten days", "Days & Counters"],
];

const VOCAB = RAW_VOCAB.map(([jp, reading, romaji, en, category], i) => ({ id: i, jp, reading, romaji, en, category }));
const CATEGORIES = [...new Set(VOCAB.map(v => v.category))];
